accounts/urls.py
from django.conf.urls import url
import views as user_views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    
    url(r'^create/', user_views.UserCreate.as_view(), name='create-user'),
    url(r'^details/(?P<pk>[-\w]+)/', user_views.UserDetails.as_view(), name='user-details'),
    url(r'^delete/(?P<pk>[-\w]+)/', user_views.UserDelete.as_view(), name='delete-user'),
    url(r'^edit/(?P<pk>[-\w]+)/', user_views.UserEdit.as_view(), name='update-user'),
    url(r'^export/', user_views.ExportToExcel.as_view(), name='user-list-export'),
]

python_code_task/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import accounts.views as user_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('accounts.urls')),
    url(r'^', user_views.UserListView.as_view(), name='user-list'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse_lazy
import random
import datetime


def random_num():
    return random.randint(1, 100)


class User(AbstractUser):
    birthday = models.DateField()
    random_number = models.IntegerField(default=random_num)

    def get_absolute_url(self):
        return reverse_lazy("user-details", kwargs={'pk': self.id})

    def __unicode__(self):
        return self.username

accounts/forms.py
from django import forms
from .models import User


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'birthday')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

accounts/views.py
from django.views.generic.base import View
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse

from .forms import UserCreationForm
from .utils import write_to_excel

import models as user_models

class UserListView(ListView):
    queryset = user_models.User.objects.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        return context


class UserCreate(CreateView):
    model = user_models.User
    form_class = UserCreationForm


class UserDetails(DetailView):
    model = user_models.User

    def get_context_data(self, **kwargs):
        context = super(UserDetails, self).get_context_data(**kwargs)
        return context


class UserDelete(DeleteView):
    model = user_models.User
    success_url = reverse_lazy('user-list')


class UserEdit(UpdateView):
    model = user_models.User
    fields = ['username', 'birthday']
    template_name_suffix = '_update_form'

class ExportToExcel(View):
    queryset = user_models.User.objects.all()
    content_type = 'application/vnd.ms-excel'
    filename = 'users.xlsx'

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type=self.content_type)
        response['Content-Disposition'] = 'attachment; filename=%s' % self.filename
        xlsx_data = write_to_excel(self.queryset)
        response.write(xlsx_data)
        return response

accounts/templates/accounts/user_confirm_delete.html
{% extends "base.html" %}

{% block title %}Confirm delete user{% endblock %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete user "{{ object }}"?</p>
    <input class="btn btn-default" type="submit" value="Confirm" />
</form>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends "base.html" %}

{% block content %}
<span class="pull-right"><a href="{% url 'user-list' %}">User list</a></span>
<h1>User Details</h1>
<p><strong>Username:</strong> {{ object.username }}</p>
<p><strong>Date of Birth:</strong> {{ object.birthday }}</p>

<button class="btn btn-default"><a href="{% url 'delete-user' object.id %}">Delete User</a></button>
<button class="btn btn-default"><a href="{% url 'update-user' object.id %}">Edit User</a></button>
{% endblock %}

accounts/templates/accounts/user_form.html
{% extends "base.html" %}

{% block content %}
<h1 class="center">Create new User</h1>
<form id="userForm" action="{% url 'create-user' %}" method="post" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group {% if form.username.errors %} has-error {% endif %}">
        <label class="col-xs-3 control-label">Username</label>

        <div class="col-xs-5">
          {{ form.username }}
          {% for error in form.username.errors %}
		    <span class="help-block">{{ error|escape }}</span>
		  {% endfor %}
        </div>		
    </div>

    <div class="form-group {% if form.birthday.errors %} has-error {% endif %}">
        <label class="col-xs-3 control-label">Birthday</label>
        <div class="col-xs-5">
          {{ form.birthday }}
          {% for error in form.birthday.errors %}
		    <span class="help-block">{{ error|escape }}</span>
		  {% endfor %}
        </div> 
    </div>
    
    <div class="form-group {% if form.password1.errors %} has-error {% endif %}">
        <label class="col-xs-3 control-label">Password1</label>
        <div class="col-xs-5">
          {{ form.password1 }}
          {% for error in form.password1.errors %}
		    <span class="help-block">{{ error|escape }}</span>
		  {% endfor %}
        </div> 
    </div>
    
    <div class="form-group {% if form.password2.errors %} has-error {% endif %}">
        <label class="col-xs-3 control-label">Password2</label>
        <div class="col-xs-5">
          {{ form.password2 }}
          {% for error in form.password2.errors %}
		    <span class="help-block">{{ error|escape }}</span>
		  {% endfor %}
        </div> 
    </div>
    
    <div class="form-group">
        <div class="col-xs-5 col-xs-offset-3">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
    
</form>
{% endblock %}

{% block extra_js %}

<script>
$(document).ready(function() {
    $('#id_birthday').datepicker({
                    format: "mm/dd/yyyy"
                });
     
    $("input").addClass("form-control")
 });
 </script>    
{% endblock %}

accounts/templates/accounts/user_list.html
{% extends "base.html" %}
{% load account_tags %}

{% block title %}User list{% endblock %}

{% block content %}
<div class="table-responsive">
  <table id="userlisttable" class="table text-centered">
    <thead>
      <tr>
        <th>Username</th>
        <th>Birthday</th>
        <th>Eligible</th>
        <th>Random Number</th>
        <th>BizzFuzz</th>
      </tr>
    </thead>
    <tbody>
      {% for user in object_list %}
      <tr>
        <td><a href="{% url 'user-details' user.id %}">{{ user.username }}</a></td>
        <td>{{ user.birthday }}</td>
        <td>{{ user.birthday|eligible }}</td>
        <td>{{ user.random_number }}</td>
        <td>{{ user.random_number|bizzfuzz }}</td>
      </tr>
	  {% empty %}
	  <tr>
	    <td colspan="5">No users found!.</td>
	  </tr>
	  {% endfor %}
      </tr>
    </tbody>
  </table>
</div>

<button class="btn btn-default"><a href="{% url 'create-user' %}">Create a new User</a></button>
<div class="text-center">
<span><a href="{% url 'user-list-export' %}">Export</a></span>
</div>
{% endblock %}

accounts/templates/accounts/user_update_form.html
{% extends "base.html" %}

{% block content %}
<h1 class="center">Update User {{ form.username.value }}</h1>
<form id="userForm" action="{% url 'update-user' object.id %}" method="post" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group {% if form.username.errors %} has-error {% endif %}">
        <label class="col-xs-3 control-label">Username</label>
        <div class="col-xs-5">
          {{ form.username }}
          {% for error in form.username.errors %}
		    <span class="help-block">{{ error|escape }}</span>
		  {% endfor %}
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-3 control-label">Birthday</label>
        <div class="col-xs-5">
          {{ form.birthday }}
          {% for error in form.birthday.errors %}
		    <span class="help-block">{{ error|escape }}</span>
		  {% endfor %}
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-5 col-xs-offset-3">
            <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
    
</form>
{% endblock %}

{% block extra_js %}

<script>
$(document).ready(function() {
    $('#id_birthday').datepicker({
                    format: "mm/dd/yyyy"
                });
    $("input").addClass("form-control")
 });
 </script>    
{% endblock %}

python_code_task/templates/base.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>{% block title %}{% endblock %}</title>
  <meta name="description" content="Python test task">
  <meta name="author" content="Test">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Include Bootstrap Datepicker -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />

  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>

  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
  <style type="text/css">  
    .center-block {
        width:80%;
        margin-top: 30px;
        padding:10px;  
        background-color:#eceadc;
    }
    .center {
		margin: auto;
		width: 50%;
		padding: 10px;
	}
    #userlisttable>tbody>tr>td a{
        display: block;
    }
  </style>
</head>
<body>
  <div class="container-fluid">
    <div class="row">  
      <div class="center-block">
        {% block content %}
        {% endblock %}
      </div>
      
    </div>
  </div>
</body>
{% block extra_js %}
{% endblock %}
</html>